using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Text;

internal static class SourceGeneratorExtentions
{
    public static void AppendResources(this StringBuilder stringBuilder, string resourceName, Assembly assembly, int countTabs, Dictionary<string, string> stringsForReplace = default)
    {
        string[] lines = SourceGeneratorUtils.LoadTemplateLines(resourceName, assembly);
        for (int i = 0; i < lines.Length; i++)
        {
            var line = lines[i];
            if (stringsForReplace != null)
            {
                foreach (var pair in stringsForReplace)
                {
                    if (line.Contains(pair.Key))
                    {
                        line = line.Replace(pair.Key, pair.Value);
                    }
                }
            }
            stringBuilder.AppendLineWithTab(line, countTabs);
        }
    }

    public static void AppendLineWithTab(this StringBuilder stringBuilder, string @string, int countTabs)
    {
        stringBuilder.AppendLine(new string('\t', countTabs) + @string);
    }

    public static void AppendTabs(this StringBuilder stringBuilder, int countTabs)
    {
        stringBuilder.AppendLine(new string('\t', countTabs));
    }

    public static void AppendTab(this StringBuilder stringBuilder)
    {
        stringBuilder.AppendLine("\t");
    }

    //public static void AppendPartialTypeHeader(this StringBuilder stringBuilder, int countTabs)
    //{
    //    // 3) модификаторы, 6) доступность, 4) дженерики + where
    //    var accessibility = GetAccessibility(s);
    //    var modifiers = GetModifiers(s);
    //    var typeKeyword = GetTypeKeyword(s);
    //    var typeParams = GetTypeParameterList(s);
    //    var whereClauses = BuildWhereClauses(s);

    //    if (addGeneratedAttributes)
    //    {
    //        stringBuilder.AppendLineWithTab("[global::System.CodeDom.Compiler.GeneratedCode(\"LoggingSourceGenerator\", \"1.0.0\")]", countTabs);
    //        stringBuilder.AppendLineWithTab("[global::System.Diagnostics.DebuggerNonUserCode]", countTabs);
    //        stringBuilder.AppendLineWithTab("[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]", countTabs);
    //    }

    //    stringBuilder.AppendLineWithTab($"{accessibility}{modifiers} partial {typeKeyword} {s.Name}{typeParams}", countTabs);
    //    foreach (var clause in whereClauses)
    //        stringBuilder.AppendLineWithTab(clause, countTabs);

    //    stringBuilder.AppendLineWithTab("{", countTabs);
    //}

    public static void AppendDefaultGeneratedLines(this StringBuilder stringBuilder)
    {
        stringBuilder.AppendLine("// <auto-generated/>");
        stringBuilder.AppendLine("#nullable enable");
        stringBuilder.AppendLine();
    }
}
